name: Deploy

on:
  push:
    branches:
      - master

jobs:

# Do something

 build:
    runs-on: ubuntu-latest
  steps:
    run: echo "hello world " 
  
  test:
    runs-on: ubuntu-latest
  steps:
    run: echo hello world

  build:
   needs: test 
   runs-on: ubuntu-latest
  steps:
    run: echo "hello world "
