name: Deploy and test

on:
  push:
    branches:
      - master

jobs:

# Do something

 build:
    runs-on: ubuntu-latest
  steps:
  - name: first try
    run: echo "hello world " 
  
  test:
    runs-on: ubuntu-latest
  steps:
  - name: second try
    run: echo "hello world"

  deploy:
   needs: test 
   runs-on: ubuntu-latest
  steps:
  - name: third try
    run: echo "hello world "
